#!/bin/sh
#PBS -N kiat-imb
#PBS -j oe
#PBS -A UT-NTNL0087

### Unused PBS options ###
## If left commented, must be specified when the job is submitted:
## 'qsub -l walltime=hh:mm:ss,nodes=12:ppn=4'
##
##PBS -l walltime=00:30:00
##PBS -l nodes=8:ppn=3

### End of PBS options ###

#Set the number of processes here or in a script that calls this
#job script
num_procs=8


# run the program

which mpirun
mpirun -machinefile $PBS_NODEFILE -np $num_procs test_bfs_4.2_x86_64 grid2d 10 --num-nodes=$num_procs
date

# eof
